### ISSUE TITLE
Scratch with F6 npm issue

### ISSUE THREAD

**Issue by fransy-halo** [sixteenbit/generator-scratch#3]
Hi, grunt does not work. here is the error details:

`npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "darwin"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! file /Applications/MAMP/htdocs/dev/example.com/wp-content/themes/example/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 44:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Applications/MAMP/htdocs/dev/example.com/wp-content/themes/example/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse`

The npm-debug.log file is attached.
[npm-debug.log.zip](https://github.com/sixteenbit/generator-scratch/files/376442/npm-debug.log.zip)

Thanks

**Comment by justin-peacock** [comment]
Hey @fransy-halo I haven't worked on this project in a while so it's probably out of date. I need to rebuild it. Maybe when I get some free time.

**Comment by justin-peacock** [comment]
Hey @fransy-halo,

Just letting you know I've completely re-written the generator and it's now published on https://www.npmjs.com/package/generator-scratch. Let me know if you run into any issues.

**Comment by fransy-halo** [comment]
Thanks  @mrdink ,

This command line adds the generator without .gitignore so when running yo scratch it does not work. I found the way around by copying the files from github in the node_modules folder.

For your reference attached is the was the error I got.
![1__bash_and_live_-_lesteraldridge_com](https://cloud.githubusercontent.com/assets/12528023/18203144/d7154bee-710c-11e6-8525-40ee31678ea4.png)

Other than that, it's great. Thanks!

**Comment by justin-peacock** [comment]
Did you try installing using the following?

`npm install -g generator-scratch`

Also what version of Yeoman are you running?

Thanks for helping me debug!

Edit: I think I know the issue.

**Comment by justin-peacock** [comment]
@fransy-halo I just pushed an update. Run `npm install -g generator-scratch` and it should update to v0.1.7. Let me know if that fixes it for you.

**Comment by fransy-halo** [comment]
Hi @mrdink it works now :) without my hack. 
Only thing,  it does not detect my yo version. I've installed yo 1.8.5 but it gives and WARN.
![1__bash](https://cloud.githubusercontent.com/assets/12528023/18205471/0c4395ca-711a-11e6-8f93-d152c5a1e1f0.png)
Thanks!
